
export const tripPackagesSeed = [
  {
    slug: "kashmir-blossom-sisterhood",
    destinationSlug: "kashmir",
    isInternational: false,
    title: "Kashmir Blossom - Houseboat Sisterhood",
    shortDescription: "5D/4N Srinagar-Gulmarg-Pahalgam women-only spring special. Tulip garden included.",
    longDescription: "Imagine shikara rides at sunrise with only your girl gang, kahwa with stories, and a tulip garden that looks like heaven spilled. Every stay is verified, every driver is background-checked, trip leader is with you from arrival till drop. We share hotel names 7 days prior and keep a WhatsApp group active 48 hours before departure.",
    durationDays: 5,
    durationNights: 4,
    priceFrom: 21999,
    priceOriginal: 25999,
    groupSizeMin: 8,
    groupSizeMax: 16,
    difficulty: "easy",
    comfortLevel: "comfort",
    isWomenOnly: true,
    isFeatured: true,
    isFamilyFriendly: true,
    heroImage: "https://images.unsplash.com/photo-1595815771613-e38f95959446?w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1595815771613-e38f95959446?w=1200&q=80",
      "https://images.unsplash.com/photo-1526772661823-3f88f33771cd?w=1200&q=80",
    ],
    highlights: ["Tulip Garden VIP Entry", "1N Houseboat Stay", "Women Trip Leader 24x7", "Kahwa & Wazwan Experience"],
    ratingAvg: "4.9",
    ratingCount: 212,
    itineraryChangePolicy: "In case of weather, curfew, or safety advisory, itinerary may change. You will be informed 12 hours prior with alternatives. No cost cutting.",
  },
  {
    slug: "kerala-backwater-healing",
    destinationSlug: "kerala",
    isInternational: false,
    title: "Kerala - Backwater & Spice Healing Retreat",
    shortDescription: "6D/5N for mothers, daughters & friends. Houseboat + Ayurveda + tea factory sorority.",
    longDescription: "Slow travel for women who do everything for everyone else. Ayurvedic massage by women therapists, cooking with Amma, spice plantation walks.",
    durationDays: 6,
    durationNights: 5,
    priceFrom: 24999,
    priceOriginal: 28999,
    groupSizeMin: 6,
    groupSizeMax: 14,
    difficulty: "easy",
    comfortLevel: "premium",
    isWomenOnly: true,
    isFeatured: true,
    heroImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=80",
    gallery: [],
    highlights: ["Women-led Houseboat", "Ayurveda Session", "Tea Trail Trek", "Spice Market with Guide"],
    ratingAvg: "4.8",
    ratingCount: 189,
    itineraryChangePolicy: "Monsoon water level changes will be communicated. Boat upgrade if needed at our cost.",
  },
  {
    slug: "meghalaya-living-roots",
    destinationSlug: "meghalaya",
    isInternational: false,
    title: "Meghalaya - Living Roots & Waterfalls",
    shortDescription: "5D/4N Dawki, Cherrapunji & Mawkdok. Homestays run by women, trek graded.",
    longDescription: "Meghalaya is matrilineal - women own land, and now they lead your trek. Double decker root bridge with safety rope team.",
    durationDays: 5,
    durationNights: 4,
    priceFrom: 19999,
    priceOriginal: 23999,
    groupSizeMin: 10,
    groupSizeMax: 15,
    difficulty: "moderate",
    comfortLevel: "comfort",
    isWomenOnly: true,
    isFeatured: true,
    heroImage: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=80",
    gallery: [],
    highlights: ["Dawki Crystal Boat", "Double Decker Trek with Local Women", "Homestay Experience"],
    ratingAvg: "4.9",
    ratingCount: 156,
    itineraryChangePolicy: "Rain may delay treks. Alternative waterfall visits. Safety over itinerary.",
  },
  {
    slug: "rajasthan-queens-trail",
    destinationSlug: "rajasthan",
    isInternational: false,
    title: "Rajasthan - Queens Trail",
    shortDescription: "7D/6N Jaipur-Jodhpur-Jaisalmer with desert camp women-only zone.",
    longDescription: "Block printing with women artisans in Jaipur, cooking at a Haveli run by women, and a desert camp with private enclosure for TripNaari.",
    durationDays: 7,
    durationNights: 6,
    priceFrom: 28999,
    priceOriginal: 32999,
    groupSizeMin: 8,
    groupSizeMax: 16,
    difficulty: "easy",
    comfortLevel: "comfort",
    isWomenOnly: true,
    isFeatured: true,
    heroImage: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200&q=80",
    gallery: [],
    highlights: ["Women Artisan Workshop", "Private Desert Zone", "Folk Night"],
    ratingAvg: "4.8",
    ratingCount: 203,
    itineraryChangePolicy: "Desert wind advisory may shift camp. Backup resort included.",
  },
  {
    slug: "spiti-winter-whites",
    destinationSlug: "himachal",
    isInternational: false,
    title: "Spiti Winter Whites - Women Only 4x4",
    shortDescription: "8D/7N for the fearless. Monasteries, snow leopards & chai with nuns.",
    longDescription: "Not for everyone, only for fierce. 4x4 with trained drivers, oxygen kit, and trip leader with high-altitude certification.",
    durationDays: 8,
    durationNights: 7,
    priceFrom: 34999,
    priceOriginal: 39999,
    groupSizeMin: 6,
    groupSizeMax: 10,
    difficulty: "challenging",
    comfortLevel: "backpacker",
    isWomenOnly: true,
    isFeatured: false,
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
    gallery: [],
    highlights: ["Comics Village", "Key Monastery Private Prayer", "Women-led Kitchen"],
    ratingAvg: "4.9",
    ratingCount: 98,
    itineraryChangePolicy: "Snow blocks change route. 100% refund if trip cancelled by us due to safety.",
  },
  {
    slug: "goa-gokarna-surf-sisters",
    destinationSlug: "goa",
    isInternational: false,
    title: "Goa & Gokarna Surf Sisters",
    shortDescription: "4D/3N beach, brunch, surf lesson with female instructor and safe villa.",
    longDescription: "Weekend getaway designed for Instagram girls who want to actually live, not just post. Surf by women instructors, cafe list curated, no unwanted attention stays.",
    durationDays: 4,
    durationNights: 3,
    priceFrom: 14999,
    priceOriginal: 17999,
    groupSizeMin: 6,
    groupSizeMax: 12,
    difficulty: "easy",
    comfortLevel: "comfort",
    isWomenOnly: true,
    isFeatured: true,
    heroImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=80",
    gallery: [],
    highlights: ["Surf Lesson Women Instructor", "Beach Villa Women-Only Floor", "Brunch Trail"],
    ratingAvg: "4.7",
    ratingCount: 342,
    itineraryChangePolicy: "Tide timings may shuffle surf slot. Backup yoga included.",
  },
  {
    slug: "tirthan-whispers",
    destinationSlug: "himachal",
    isInternational: false,
    title: "Tirthan & Jibhi Whispering Pines",
    shortDescription: "3D/2N Himalayan homestay. For solo first timers from Bangalore.",
    longDescription: "Perfect first solo trip - direct Volvo pickup, verified homestay auntie, bonfire stories.",
    durationDays: 3,
    durationNights: 2,
    priceFrom: 9999,
    priceOriginal: 12499,
    groupSizeMin: 6,
    groupSizeMax: 12,
    difficulty: "easy",
    comfortLevel: "comfort",
    isWomenOnly: true,
    isFeatured: true,
    heroImage: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80",
    gallery: [],
    highlights: ["Waterfall Hike", "Homestay Auntie Cooking", "No City Stress"],
    ratingAvg: "4.8",
    ratingCount: 167,
    itineraryChangePolicy: "Landslide detour may add 2 hours. We provide lunch in that case.",
  },
  {
    slug: "bali-divine-feminine",
    destinationSlug: "international",
    isInternational: true,
    title: "Bali - Divine Feminine Retreat",
    shortDescription: "6D/5N Ubud + Uluwatu. For entrepreneurs & creatives needing reset.",
    longDescription: "Balinese priestess blessing, rice terrace healing, co-working villa for women.",
    durationDays: 6,
    durationNights: 5,
    priceFrom: 54999,
    priceOriginal: 64999,
    groupSizeMin: 8,
    groupSizeMax: 12,
    difficulty: "easy",
    comfortLevel: "premium",
    isWomenOnly: true,
    isFeatured: true,
    isFamilyFriendly: false,
    heroImage: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&q=80",
    gallery: [],
    highlights: ["Priestess Purification", "Co-work Villa", "Beach Club"],
    ratingAvg: "4.9",
    ratingCount: 88,
    itineraryChangePolicy: "Visa delay insurance guidance. Temple closures alternate.",
  },
];

export const tripLeadersSeed = [
  {
    slug: "anjali-mehra",
    name: "Anjali Mehra",
    bio: "Mountaineer from Manali, 80+ Himalayan trips led. Wilderness first responder. She carries extra hot water bottles, not just first aid.",
    specialties: ["Himachal", "Kashmir", "High Altitude"],
    languages: ["Hindi", "English", "Pahadi"],
    experienceYears: 6,
    tripsLed: 124,
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    isVerified: true,
  },
  {
    slug: "safa-khan",
    name: "Safa Khan",
    bio: "Kerala born, Mumbai based. Ayurveda enthusiast. Makes sure every girl gets the window seat at least once.",
    specialties: ["Kerala", "Goa", "Wellness"],
    languages: ["Malayalam", "Hindi", "English"],
    experienceYears: 4,
    tripsLed: 89,
    image: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&q=80",
    isVerified: true,
  },
  {
    slug: "pema-lhamu",
    name: "Pema Lhamu",
    bio: "Khasi matriarch guide. Knows every waterfall whisper. Runs women homestay collective in Cherrapunji.",
    specialties: ["Meghalaya", "Arunachal", "Northeast"],
    languages: ["Khasi", "English", "Hindi"],
    experienceYears: 7,
    tripsLed: 102,
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    isVerified: true,
  },
];

export const testimonialsSeed = [
  {
    name: "Dr. Sneha R.",
    location: "Bangalore, 32, Solo First Timer",
    tripSlug: "kashmir-blossom-sisterhood",
    rating: 5,
    content: "I was terrified to travel solo after marriage. TripNaari didn't just ensure safety, they gave me 12 sisters. Trip leader Anjali waited till I video-called my husband from Dal Lake. Transparent hotel reveal happened 8 days before. No hidden cost.",
    isFeatured: true,
  },
  {
    name: "Lakshmi & Daughter (14)",
    location: "Chennai, Mother-Daughter Duo",
    tripSlug: "kerala-backwater-healing",
    rating: 5,
    content: "As a single mom, safety for my daughter is everything. Women-only boat, women therapist, no awkwardness. They even arranged Jain food as requested in form.",
    isFeatured: true,
  },
  {
    name: "Zoya Ahmed",
    location: "Delhi, Entrepreneur, 28",
    tripSlug: "meghalaya-living-roots",
    rating: 5,
    content: "Pema didi literally held my hand during double decker trek. Never felt like a customer. Felt like community. Refund policy is crystal clear - my friend got refund in 6 days when she cancelled for emergency.",
    isFeatured: true,
  },
  {
    name: "Savitri Devi",
    location: "Jaipur, 58, Adventurous Grandmother",
    tripSlug: "rajasthan-queens-trail",
    rating: 5,
    content: "Umar ka koi bandhan nahi! I danced in desert with girls half my age. TripNaari ensured ground floor room without me asking.",
    isFeatured: true,
  },
];

export const faqsSeed = [
  {
    question: "Is TripNaari only for solo women? Can I join with my mother or daughter?",
    answer: "TripNaari is women-first, not women-only exclusive. Our group departures are women-only (including trans women). We welcome mothers, daughters (12+), grandmothers, sisterhood groups. Private custom trips can include family if at least 70% travelers are women and everyone agrees to our safety code.",
    category: "general",
  },
  {
    question: "How do you ensure safety? What if I’m traveling first time?",
    answer: "Every TripNaari departure has: 1 verified women trip leader with 24x7 accountability, 2 background-checked drivers, 3 hotel safety audit (lock, location, reviews by solo women), 4 emergency contact card with local police, hospital & TripNaari escalation (Anjali 24x7), 5 live location sharing on travel days, 6 WhatsApp group made 48 hours before. First-timers get a pre-trip call.",
    category: "safety",
  },
  {
    question: "When will I know my exact hotel names?",
    answer: "We show you hotel category and 2 sample properties at booking. Exact hotel name is confirmed 7-10 days before departure (3 days for weekend trips) via email & WhatsApp. If we change hotel post-confirmation, it will be same or higher category at our cost.",
    category: "booking",
  },
  {
    question: "What is your cancellation refund timeline?",
    answer: "30+ days before: 90% refund, 15-29 days: 50% refund + 50% credit, 7-14 days: 30% refund + 50% credit, <7 days: No refund but 70% credit valid 1 year. Refunds processed in 7-10 working days to source. Credits are transferable to another Naari.",
    category: "cancellation",
  },
  {
    question: "What if weather, traffic, or low group size changes itinerary?",
    answer: "Safety first, always. If weather/political curb/traffic requires change, trip leader will offer best alternative with group vote. If group size drops below 6, we give you choice: 1) Move to next date with upgrade, 2) Continue with small group supplement (max 10% extra), 3) Full refund. We never cancel without your consent if you have confirmed date.",
    category: "booking",
  },
  {
    question: "Are inclusives and exclusives really transparent?",
    answer: "Yes. On every trip page we list exact inclusions: stay type, meals (B/D), transport (Tempo traveler/4x4), entry fees, permits, trip leader fee, first aid. Exclusions always: personal expenses, any meal not mentioned, adventure activity insurance, Tips (optional). No hidden snow boots rent.",
    category: "booking",
  },
];

export const policiesSeed = [
  {
    slug: "cancellation-refund",
    title: "Cancellation & Refund Policy - Transparent & Time-bound",
  },
  {
    slug: "safety-promise",
    title: "Safety Promise & Women-Led Accountability",
  },
  {
    slug: "privacy-policy",
    title: "Privacy Policy - Your Data, Your Sisterhood",
  },
  {
    slug: "terms-conditions",
    title: "Terms & Conditions",
  },
];

export const blogSeed = [
  {
    slug: "solo-first-trip-checklist",
    title: "First Solo Trip as Indian Woman? 17-point Safety Checklist from 3000+ Trips",
    excerpt: "Not just pepper spray. What our trip leaders actually check before you sleep at night.",
    category: "Safety",
    tags: ["solo", "safety", "checklist"],
  },
  {
    slug: "kashmir-is-safe-for-women-2026",
    title: "Is Kashmir Safe for Solo Women in 2026? Honest Review",
    excerpt: "We took 400+ women. Here’s what changed, what to wear, where not to go after dark.",
    category: "Guides",
    tags: ["kashmir", "safety"],
  },
  {
    slug: "kerala-jain-food-guide",
    title: "How We Arrange Jain, Vegan & Kid Friendly Meals in Kerala",
    excerpt: "Behind the scenes of our food preference form that actually works.",
    category: "Food",
    tags: ["kerala", "food"],
  },
];
