import { NextResponse } from "next/server";
import { getMergedTrips } from "@/lib/public-store";

function isAdminAuthenticated(req: Request) {
  const cookie = req.headers.get("cookie") || "";
  return cookie.includes("tripnaari_admin=authenticated");
}

export async function POST(req: Request) {
  try {
    // 1. Security Check
    if (!isAdminAuthenticated(req)) {
      return NextResponse.json({ error: "Unauthorized — Admin session required" }, { status: 401 });
    }

    const body = await req.json();
    const { prompt, tone = "exciting" } = body;

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required to generate notifications" }, { status: 400 });
    }

    // Get active trips to provide context
    const activeTrips = getMergedTrips() || [];
    const tripsContext = activeTrips.map((t: any) => ({
      title: t.title,
      slug: t.slug,
      priceFrom: t.priceFrom,
    }));

    const apiKey = process.env.GEMINI_API_KEY;

    // 2. Demo Mode Fallback
    if (!apiKey || apiKey === "your_key_here" || apiKey === "re_xxxxxxxxxxxxxxxx") {
      return NextResponse.json({
        success: true,
        isDemo: true,
        ideas: generateDemoNotificationIdeas(prompt, tone, tripsContext),
      });
    }

    // 3. Build System Prompt
    const systemPrompt = `You are NaariAI, TripNaari's marketing and safety copywriter for push notifications. 
TripNaari is a secure, women-only group travel company.
Your job is to generate exactly 3 distinct, highly engaging push notification drafts based on the admin's prompt and chosen tone.

Here is the list of active trips currently available:
${JSON.stringify(tripsContext, null, 2)}

Ensure the ideas fit these strict rules:
1. "title": Must be short (max 50 characters) and include 1-2 relevant emojis. Should be extremely catchy.
2. "message": Must be concise (max 150 characters), speak directly to women solo travelers, focus on safety/sisterhood, and end with a call to action.
3. "url": Relative path to a trip like "/trips/<slug>" (using slug from active trips that matches the prompt) or "/trips" (to browse all) or "/" for homepage. Select the most relevant URL.

You must return a valid JSON array of exactly 3 objects.
Each object must have exactly these keys: "title", "message", and "url".
Output ONLY the raw JSON array. Do not include markdown codeblocks (like \`\`\`json) or any conversational intro/outro.`;

    const userPrompt = `Generate 3 push notification drafts for this request: "${prompt}" using a "${tone}" tone.`;

    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

    const apiResponse = await fetch(apiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [{ text: userPrompt }],
          },
        ],
        systemInstruction: {
          parts: [{ text: systemPrompt }],
        },
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 800,
          responseMimeType: "application/json",
        },
      }),
    });

    if (!apiResponse.ok) {
      const errorData = await apiResponse.json().catch(() => ({}));
      console.error("Gemini API Error:", errorData);
      // Fallback to demo mode if API call fails
      return NextResponse.json({
        success: true,
        isDemo: true,
        ideas: generateDemoNotificationIdeas(prompt, tone, tripsContext),
      });
    }

    const responseData = await apiResponse.json();
    const replyText = responseData?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!replyText) {
      throw new Error("No content generated by Gemini");
    }

    // Parse output JSON
    const ideas = JSON.parse(replyText.trim());

    return NextResponse.json({
      success: true,
      isDemo: false,
      ideas: Array.isArray(ideas) ? ideas.slice(0, 3) : [],
    });

  } catch (error: any) {
    console.error("AI Generation Error:", error);
    // Safe fallback to demo content on error
    try {
      const trips = getMergedTrips() || [];
      const context = trips.map((t: any) => ({ title: t.title, slug: t.slug }));
      return NextResponse.json({
        success: true,
        isDemo: true,
        ideas: generateDemoNotificationIdeas(req.headers.get("x-prompt") || "alert", "exciting", context),
      });
    } catch {
      return NextResponse.json({ success: false, error: "Internal Server Error" }, { status: 500 });
    }
  }
}

// Generate high-quality template ideas in demo mode
function generateDemoNotificationIdeas(prompt: string, tone: string, trips: any[]): any[] {
  const p = prompt.toLowerCase();
  
  // Find matching trip or fallback to random
  let matchedTrip = trips[0] || { title: "Kashmir Blossom Sisterhood", slug: "kashmir-blossom-sisterhood" };
  for (const t of trips) {
    if (p.includes(t.title.toLowerCase()) || p.includes(t.slug.split("-")[0])) {
      matchedTrip = t;
      break;
    }
  }

  const tripName = matchedTrip.title;
  const tripUrl = `/trips/${matchedTrip.slug}`;

  if (p.includes("discount") || p.includes("offer") || p.includes("price") || tone === "promotional") {
    return [
      {
        title: `⚡ Deal Alert: ₹5,000 Off on ${tripName}!`,
        message: `Grab our limited sisterhood discount. Verified hotels, female trip leader, & safe transfers included. Tap to claim coupon!`,
        url: tripUrl,
      },
      {
        title: `🎟️ Early-Bird Special: Travel Safe!`,
        message: `Secure your slot for upcoming departures to ${tripName.split(" ")[0]}. Handcrafted safe itinerary, 24x7 support. Code: EARLYBIRD.`,
        url: "/trips",
      },
      {
        title: `🎒 Dream Travel, Safe Budget!`,
        message: `Explore solo women travel to ${tripName} without breaking the bank. Secure group size limited to 12. Tap for details!`,
        url: tripUrl,
      },
    ];
  }

  if (p.includes("safety") || p.includes("secure") || tone === "safety") {
    return [
      {
        title: `🛡️ TripNaari Safety Promise 🌸`,
        message: `How we audit every homestay room lock and verify all transport drivers before you check in. Read our safety guidelines here.`,
        url: "/policies/safety-promise",
      },
      {
        title: `👩‍✈️ Travel Solo but Never Alone!`,
        message: `Meet your female trip leader and a circle of safety. Explore safe travel to ${tripName} starting next month.`,
        url: tripUrl,
      },
      {
        title: `📞 24x7 Emergency Concierge Live`,
        message: `Our Bangalore-based women safety command center tracks all group movements live. Tap to see how we backpack fearless!`,
        url: "/safety",
      },
    ];
  }

  if (p.includes("last") || p.includes("urgent") || tone === "urgent") {
    return [
      {
        title: `⚠️ Last 2 Slots: ${tripName}!`,
        message: `Group booking for our next group departure closes tonight. Travel with 12 amazing women. Don't miss out!`,
        url: tripUrl,
      },
      {
        title: `⏰ Hurry! Flights price rising!`,
        message: `Kashmir & Meghalaya group departures are filling fast. Secure your spot with a token deposit. Tap to book.`,
        url: "/trips",
      },
      {
        title: `🎒 Your Backpack is Waiting!`,
        message: `Escape the routine! Connect with your sisterhood in ${tripName.split(" ")[0]}. Book now before it sells out.`,
        url: tripUrl,
      },
    ];
  }

  // Default wanderlust/exciting ideas
  return [
    {
      title: `🌸 Discover ${tripName} with Sisters!`,
      message: `Join a safe circle of solo women travelers. Handcrafted itinerary, scenic treks, and verified stays. Tap to explore departures!`,
      url: tripUrl,
    },
    {
      title: `🎒 Wanderlust Call: Explore safely!`,
      message: `Need a getaway? Book our safe women-only group departure to ${tripName.split(" ")[0]}. Secure bookings now open.`,
      url: tripUrl,
    },
    {
      title: `✨ Find Your Sisterhood Community`,
      message: `Over 3000+ women have backpacked fearless with TripNaari. Tap to join the chat and plan your next destination!`,
      url: "/",
    },
  ];
}
